version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-minor-and-patch-dependency-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
    - dependency-name: "dash-mantine-components"
      # Ignore versions that are greater than below
      versions: [ ">0.13.0.a3" ]